version: 2
plan:
  project-key: WEB
  key: PLAN
  name: My Plan

stages:
  - Stage 1:
      jobs:
        - Job 1

Job 1:
  tasks:
    - script:
        - docker run --rm --add-host qa.fortidevsec.forticloud.com:10.34.160.14 --mount type=bind,source="$PWD",target=/scan  dops-registry.fortinet-us.com/fortidevsecops/fdevsec_sast:latest
